[package]
name = "examine_vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.27.0"
eframe = "0.27.0"
nix = { version = "0.29.0", features = ["process", "uio"] }
